apiVersion: v1
kind: Service
metadata:
  name: ${variables.appName}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ${variables.appName}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${variables.appName}
  labels:
    app: ${variables.appName}
spec:
  replicas: ${variables.replicas}
  selector:
    matchLabels:
      app: ${variables.appName}
  template:
    metadata:
      labels:
        app: ${variables.appName}
    spec:
      containers:
      - name: ${variables.appName}
        image: ${variables.image}
        resources:
          requests:
            cpu: ${variables.cpuRequest}
            memory: ${variables.memoryRequest}
          limits:
            cpu: ${variables.cpuLimit}
            memory: ${variables.memoryLimit}
